# Generated by Django 5.2.1 on 2025-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_phonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('f', 'founder'), ('m', 'member')], default='m', max_length=1),
        ),
    ]
