# Generated by Django 5.2.1 on 2025-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_phonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
