# Generated by Django 5.2.1 on 2025-06-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDeskMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('founder', 'founder'), ('colaborator', 'colaborator')], default='colaborator', max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workdeskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workdesk.workdesk')),
            ],
        ),
        migrations.AddField(
            model_name='workdesk',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborator', through='workdesk.WorkDeskMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
