# Generated by Django 5.2.1 on 2025-06-06 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdesk',
            name='collaborators',
            field=models.ManyToManyField(related_name='workdeskCollaborator', through='workdesk.WorkDeskMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workdesk',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdeskCraetor', to=settings.AUTH_USER_MODEL),
        ),
    ]
