# Generated by Django 5.2.1 on 2025-06-07 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_rename_title_project_projecttitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('dedline', models.DateTimeField()),
                ('taskStatus', models.CharField(choices=[('to do', 'to-do'), ('doing', 'doing'), ('done', 'done')], default='to do', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('doers', models.ManyToManyField(related_name='taskdoers', to=settings.AUTH_USER_MODEL)),
                ('taskProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
