# Generated by Django 5.2.1 on 2025-06-07 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workdesk', '0004_alter_workdeskmembership_workdeskname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('collaborators', models.ManyToManyField(related_name='projectCollaborators', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectCraetor', to=settings.AUTH_USER_MODEL)),
                ('workdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workdesk.workdesk')),
            ],
        ),
    ]
