# Generated by Django 5.2.1 on 2025-06-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='projectTitle',
        ),
    ]
